### ISSUE TITLE
Release to bower

### ISSUE THREAD

**Issue by wingedfox** [jasondavies/bloomfilter.js#20]
It would be great to see this package in bower.io registry

**Comment by gabegorelick** [comment]
Bower isn't recommended for new projects. See https://bower.io/blog/2017/how-to-migrate-away-from-bower/.

![image](https://user-images.githubusercontent.com/610129/39552559-5961f9ac-4e2f-11e8-804b-6af6bf2ea1bb.png)

I think this can be closed.

**Comment by wingedfox** [comment]
Wow, finally there's the answer :)
