### ISSUE TITLE
Is remove function on the plan?

### ISSUE THREAD

**Issue by jameslastchina** [jasondavies/bloomfilter.js#22]
It seems counting has not implemented.How to remove the  locations of a element from the bitmap?

**Comment by pchaigno** [comment]
@jameslastchina I don't think that's possible without a counting Bloom filter.

**Comment by nickzuber** [comment]
Yeah you wouldn't be able to remove an item without rebuilding the bitarray, which can be pretty expensive. So generally I don't think bloom filter data structures really have a delete method for that reason.

**Comment by jasondavies** [comment]
No plans to implement this right now.  As mentioned, a counting bloom filter or similar data structure would be required.
