### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jinwoo** [jasondavies/bloomfilter.js#27]
First of all, thank you for the great implementation of Bloom Filter. We're using this package from our [`h2-auto-push`](https://www.npmjs.com/package/h2-auto-push) package, and it's working great.

But I want to make sure we have no license problems by depending on this package. Your [LICENSE](https://github.com/jasondavies/bloomfilter.js/blob/master/LICENSE) file looks similar to [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) but not quite the same. Can I understand it as BSD-3-Clause?

If my understanding is correct, can you please put the license info into your `package.json`? Because it is missing, the npm page says "license: none": https://www.npmjs.com/package/bloomfilter. It'll be as simple as adding this line:
```json
{ "license" : "BSD-3-Clause" }
```
https://docs.npmjs.com/files/package.json#license

Thank you!

**Comment by pchaigno** [comment]
Replacing the license file with one of those from https://choosealicense.com/ would also allow [GitHub to recognize and display it](https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/).

**Comment by jinwoo** [comment]
Awesome. Thanks, @jasondavies , for the super-quick fix!
