### ISSUE TITLE
is it possible to calculate index?

### ISSUE THREAD

**Issue by thearthouse** [jasondavies/bloomfilter.js#32]
like
['ant', 'bison'].indexOf('ant')
>0

**Comment by jasondavies** [comment]
Can you explain in a bit more detail?

**Comment by thearthouse** [comment]
in normal array 
beasts = ['ant', 'bison', 'camel', 'duck', 'bison'];
we can get index of elements like this 
beasts.indexOf('bison') 
beasts.indexOf('duck')

in bloom lets say we add this elements 'ant', 'bison', 'camel', 'duck', 'bison'
how to calculate 'bison' index or is it possible ?

**Comment by thearthouse** [comment]
it possible ?

**Comment by jasondavies** [comment]
In a bloom filter, a given element doesn't necessarily have single index.  The closest equivalent would be to get the positions in the bit vector (which you can do using `.locations()` in this library.  If you want to know about how bloom filters work, I made an interactive visualisation [here](https://www.jasondavies.com/bloomfilter/).
